wandb_version: 1

env_name:
  desc: null
  value: rodent
algo_name:
  desc: null
  value: ppo
task_name:
  desc: null
  value: gap
num_timesteps:
  desc: null
  value: 100000
num_evals:
  desc: null
  value: 1000
eval_every:
  desc: null
  value: 10000
episode_length:
  desc: null
  value: 1000
num_envs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 32
num_minibatches:
  desc: null
  value: 32
num_updates_per_batch:
  desc: null
  value: 2
unroll_length:
  desc: null
  value: 5
terminate_when_unhealthy:
  desc: null
  value: true
solver:
  desc: null
  value: cg
iterations:
  desc: null
  value: 6
ls_iterations:
  desc: null
  value: 3
vision:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713307997.0
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.10
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
